#!/usr/bin/env python3
'''
Description:    Opsview/Nagios plugin to monitor the status of a
                given container and alert if not running.
Author:         Bo Smith (bo@bosmith.tech)
Date:           2021-01-28
'''

import argparse
import json
import requests
import sys

ok = 0
warn = 1
crit = 2
unknown = 3


# Parse Arguments
###############################################################################
def get_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description='Opsview plugin to monitor container status'
    )
    required = parser.add_argument_group('Required Arguments')
    threshold = parser.add_argument_group('Threshold Arguments')
    required.add_argument(
        '-H',
        '--hostaddress',
        action='store',
        required=True,
        help='Host Address, either IP or DNS'
    )
    required.add_argument(
        '-C',
        '--container',
        action='store',
        required=True,
        help='Name of the container to check'
    )
    required.add_argument(
        '-p',
        '--port',
        action='store',
        default='4243',
        required=False,
        help='Docker API Port (Default 4243)'
    )
    required.add_argument(
        '--ssl',
        action='store_true',
        default=False,
        required=False,
        help='If this flag is passed, use https'
    )
    threshold.add_argument(
        '-w',
        '--warning',
        action='store_true',
        default=False,
        required=False,
        help='Send a WARNING alert if not running'
    )
    threshold.add_argument(
        '-c',
        '--critical',
        action='store_true',
        default=False,
        required=False,
        help='Send a CRITICAL alert if not running'
    )
    return(parser.parse_args())


# Get Status
##############################################################################
def get_status(args):
    # Build the url
    if args.ssl:
        url = 'https://'
    else:
        url = 'http://'
    url += '{}:{}/containers/{}/json'.format(
        args.hostaddress,
        args.port,
        args.container
    )

    # Get the status
    try:
        s = requests.get(
            url
        )
        s.raise_for_status
        return(s.json())
    except requests.exceptions.HTTPError as err:
        send_unknown('Unable to get status '+str(err))


# Parse Status
##############################################################################
def parse_status(args, status):
    # TODO Gather some helpful metrics such as uptime
    if status.get('message', None) is not None:
        message = status['message']
        if args.critical:
            send_critical(message)
        elif args.warning:
            send_warning(message)
        else:
            send_ok(message)
    else:
        message = "{} is {}".format(args.container, status['State']['Status'])
        if status['State']['Status'] != 'running':
            if args.critical:
                send_critical(message)
            elif args.warning:
                send_warning(message)
            else:
                send_ok(message)
        else:
            send_ok(message)


# Alert Functions
##############################################################################
def send_warning(message):
    print('WARNING - '+message)
    sys.exit(warn)


def send_critical(message):
    print('CRITICAL - '+message)
    sys.exit(crit)


def send_ok(message):
    print('OK - '+message)
    sys.exit(ok)


def send_unknown(message):
    print('UNKNOWN - '+message)
    sys.exit(unknown)


# Main - Work starts here
###############################################################################
def main():
    args = get_args()
    status = get_status(args)
    parse_status(args, status)


if __name__ == '__main__':
    main()
