#!/usr/bin/env python3
###############################################################################
'''
 Description: 		Nagios/Opsview plugin that monitors the status of Palo
			Alto Firewall bgp peers using the Palo Alto XML API
 Author:		Bo Smith (bo@bosmith.tech)
 Creation Date:	2019-01-18
 Requirements:		Requires a Palo Alto admin api key.  Highly recommend
			readonly permission be applied.
 Source: https://www.paloaltonetworks.com/documentation/71/pan-os/xml-api/get-started-with-the-pan-os-xml-api/get-your-api-key
'''
import sys
import argparse
import xml.etree.ElementTree as ET
import requests
import urllib3
import sys
import re
import pprint
# Uncomment to re-enable warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Parse Arguments
###############################################################################
parser = argparse.ArgumentParser(
    prog='check_pan_bgp_peers',
    usage='%(prog)s [-H] [-w] [-c]',
    description='Plugin for monitoring Palo Alto bgp peer status')
parser.add_argument('-H', '--host', action='store', required=True, metavar='',
                    help='Hostname or IP Address of the Firewall (Required)')
parser.add_argument('-k', '--key', action='store', required=True, metavar='',
                    help='API Key (Required)')
parser.add_argument('-C', '--connecttime', action='store', required=False, metavar='',
                    help='Connection timeout in seconds (default is 10 if not set)', default=10)
parser.add_argument('-w', '--warning', action='store_true', required=False,
                    help='Issue a warning alert of a peer is down', default=True)
parser.add_argument('-c', '--critical', action='store_true', required=False,
                    help='Issue a critical alert of a peer is down', default=False)
parser.add_argument("-W", "--whitelist", dest="whitelist",
                    action="append", default=[])
parser.add_argument("-b", "--blacklist", dest="blacklist",
                    action="append", default=[])
args = parser.parse_args()
host = args.host
key = args.key
conntime = int(args.connecttime)
warn = args.warning
crit = args.critical
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3


# Request HA data from api
###############################################################################
def get_ha_data(host, key):
    url = 'https://' + host + '/api/?type=op&cmd='
    url += '<show><high-availability><all>'
    url += '</all></high-availability></show>'
    url += '&key=' + key
    try:
        data = requests.get(url, verify=False, timeout=conntime)
        data.raise_for_status()
    except requests.exceptions.RequestException as err:
        alert_unknown('Exception encountered ' + str(err))
    return(data.content)


# Request peer data from api
###############################################################################
def get_peer_data(host, key):
    url = 'https://' + host + '/api/?type=op&cmd='
    url += '<show><routing><protocol><bgp><peer>'
    url += '</peer></bgp></protocol></routing></show>'
    url += '&key=' + key
    try:
        data = requests.get(url, verify=False, timeout=conntime)
        data.raise_for_status()
    except requests.exceptions.RequestException as err:
        alert_warning('Exception encountered ' + str(err))
    return(data.content)


# Get HA status from XML DOM
###############################################################################
def get_ha_status(data):
    try:
        dom = ET.fromstring(data)
        ha = dom.find('./result/group/local-info/state').text
    except Exception as err:
        # Exception will occur if PAN is not in an HA config
        # Populate the variable so it exists later but keep going
        ha = 'NON-HA'
    return(ha)


# Get vpn data from XML DOM
###############################################################################
def get_peer_info(data):
    all_peers = []
    try:
        dom = ET.fromstring(data)
        peers = dom.findall('./result/entry')
    except Exception as err:
        alert_warning(str(err))

    for peer in peers:
        pr = {}
        pr['entry'] = peer.attrib
        pr['status'] = peer.find('status').text
        all_peers.append(pr)
    return(all_peers)


# Process status and issue any alerts
###############################################################################
def process_status(status):
    estcount = 0
    errcount = 0
    errstatus = ''
    vpn_count = 0

    for entry in status:

        peer = (entry['entry']['peer'])
        vr = (entry['entry']['vr'])
        status = (entry['status'])
        if len(args.whitelist) > 0:
            if peer in args.whitelist:
                if status != 'Established':
                    errcount += 1
                    if errcount > 1:
                        errstatus += ", {}:{} has status {}".format(
                            peer, vr, status)
                    else:
                        errstatus += "{}:{} has status {}".format(peer, vr, status)
                else:
                    estcount += 1
        else:
            if peer not in args.blacklist:
                if 'vpn' in peer.lower():
                    vpn_count += 1
                if status != 'Established':
                    errcount += 1
                    if errcount > 1:
                        errstatus += ", {}:{} has status {}".format(
                            peer, vr, status)
                    else:
                        errstatus += "{}:{} has status {}".format(peer, vr, status)
                else:
                    estcount += 1

    perfdata = ' | peers_established=' + \
        str(estcount) + ' peer_errors=' + str(errcount)
    if errcount != 0:
        # if crit == True:
        if (errcount == 1 and vpn_count == 0) or (errcount > 1):
            alert_critical(errstatus + perfdata)
        else:
            alert_warning(errstatus + perfdata)
    else:
        alert_ok(str(estcount) + ' peers are established' + perfdata)


# Alert Handling Functions
###############################################################################
def alert_ok(output):
    print('OK - {}'.format(output))
    sys.exit(STATE_OK)


def alert_warning(output):
    print('WARNING - {}'.format(output))
    sys.exit(STATE_WARNING)


def alert_critical(output):
    print('CRITICAL - {}'.format(output))
    sys.exit(STATE_CRITICAL)


def alert_unknown(output):
    print('UNKNOWN - {}'.format(output))
    sys.exit(STATE_UNKNOWN)


# MAIN (Let it begin, LET IT BEGIN!)
###############################################################################
ha_data = get_ha_data(host, key)
ha_state = get_ha_status(ha_data)
# if the firewall is currently passive, bail out
if ha_state == 'passive':
    alert_ok('Firewall is currently passive, not checking peers')

peer_data = get_peer_data(host, key)
status = get_peer_info(peer_data)
process_status(status)
